### PR TITLE
Initial integration of notifications module with the API Gateway

### PR DESCRIPTION
**Pull request by dazanez**
A welcome endpoint responding with a message for the notifications module in the API Gateway

### CODE REVIEW

**Comment by dazanez** [comment]
@Basultobd

**Review by Basultobd — APPROVED** [review]
LGTM!

**Review by Basultobd — APPROVED** [review]
LGTM!

**Review by Basultobd — APPROVED** [review]
LGTM!

**Comment by dazanez** [comment]
#78

**Pull request merged**
